import React from 'react';
import { 
  Sparkles, 
  Award, 
  MapPin, 
  Mail, 
  Linkedin, 
  Github, 
  CheckCircle2, 
  Zap, 
  ShieldCheck, 
  FileText, 
  Mic, 
  TrendingUp, 
  Users, 
  Video, 
  Globe, 
  Briefcase, 
  Star, 
  ArrowRight,
  Code,
  Brain,
  GraduationCap
} from 'lucide-react';

interface AboutUsViewProps {
  onNavigateTab: (tab: string) => void;
  onOpenFounderModal: () => void;
}

export const AboutUsView: React.FC<AboutUsViewProps> = ({
  onNavigateTab,
  onOpenFounderModal,
}) => {
  const platformFeatures = [
    { id: 'input', label: 'ATS Resume Analyzer', icon: FileText, cat: 'Resume AI', desc: 'Sub-50ms multi-dimensional resume parsing & ATS gap detection.' },
    { id: 'builder', label: 'Interactive Resume Builder', icon: Code, cat: 'Resume AI', desc: 'Real-time drag-and-drop resume editor with AI section rewrites.' },
    { id: 'bullets', label: 'Bullet Point Metric Enhancer', icon: Zap, cat: 'Resume AI', desc: 'Quantify bullet points with STAR format metrics and action verbs.' },
    { id: 'ats', label: 'ATS Formatting Studio', icon: ShieldCheck, cat: 'Resume AI', desc: 'Parseability checks, font validation, and margin scanner.' },
    { id: 'cover', label: 'Tailored Cover Letter', icon: Mail, cat: 'Resume AI', desc: 'Role-specific executive cover letters matched to job descriptions.' },
    { id: 'portfolio', label: 'AI Web Portfolio Generator', icon: Globe, cat: 'Resume AI', desc: 'Generate live interactive portfolio web pages with 1 click.' },
    { id: 'voice-interview', label: 'Live Voice & Video AI', icon: Video, cat: 'Interview Hub', desc: 'Real-time speech evaluation, tone analysis, and posture feedback.' },
    { id: 'mock', label: 'AI Voice Mock Interview', icon: Mic, cat: 'Interview Hub', desc: 'Interactive voice interview room with instant hiring score.' },
    { id: 'interviewer', label: 'Hiring Manager Report', icon: Users, cat: 'Interview Hub', desc: 'Technical candidate scorecard generated by AI recruiters.' },
    { id: 'flashcards', label: 'Technical Flashcard Drills', icon: Brain, cat: 'Interview Hub', desc: 'Interactive flashcards covering system design, algorithms & CS.' },
    { id: 'community-hub', label: 'Alumni & Peer Network', icon: Users, cat: 'Interview Hub', desc: 'Connect with verified job candidates & industry mentors.' },
    { id: 'career', label: 'Career Pathway Roadmap', icon: TrendingUp, cat: 'Career Growth', desc: '3-year promotion blueprint with skill milestone tracking.' },
    { id: 'salary', label: 'Salary Evaluator', icon: Briefcase, cat: 'Career Growth', desc: 'Location-adjusted benchmark compensation & negotiation scripts.' },
    { id: 'offer-evaluator', label: 'Offer & Equity Evaluator', icon: Award, cat: 'Career Growth', desc: 'Analyze base salary, stock options, and equity total value.' },
    { id: 'tracker', label: 'Job Tracker CRM', icon: Briefcase, cat: 'Career Growth', desc: 'Kanban board CRM for tracking application statuses & deadlines.' },
    { id: 'jobs', label: 'Jobs & Upskill Projects', icon: Briefcase, cat: 'Platform', desc: 'Tailored job recommendations and portfolio project ideas.' },
    { id: 'chat', label: 'AI Career Coach', icon: Sparkles, cat: 'Platform', desc: '24/7 interactive career guidance chatbot powered by CAREER PLUS+ AI.' },
    { id: 'reviews', label: 'Community Reviews', icon: Star, cat: 'Platform', desc: 'Verified user reviews, success stories, and platform feedback.' },
  ];

  return (
    <div className="space-y-12 max-w-6xl mx-auto pb-12 animate-in fade-in duration-200">
      
      {/* TOP HERO BANNER */}
      <div className="relative rounded-3xl bg-gradient-to-r from-slate-900 via-blue-950 to-slate-900 p-8 sm:p-12 text-white overflow-hidden shadow-2xl border border-slate-800">
        <div className="absolute top-0 right-0 -mt-12 -mr-12 w-96 h-96 bg-blue-600/20 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 -mb-12 -ml-12 w-96 h-96 bg-indigo-600/20 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 max-w-3xl space-y-4">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-blue-500/20 border border-blue-400/30 text-amber-300 text-xs font-extrabold uppercase tracking-widest backdrop-blur-md">
            <Sparkles className="w-3.5 h-3.5 text-amber-300" />
            <span>About CAREER PLUS+ & Founder</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-white leading-tight">
            Democratizing Career Success with Next-Gen AI
          </h1>

          <p className="text-sm sm:text-base text-slate-300 leading-relaxed font-normal">
            CAREER PLUS+ is an enterprise-grade AI career intelligence platform designed to level the hiring field. Powered by our advanced CAREER PLUS+ AI Engine, we provide real-time resume optimization, ATS audit matrices, live voice & video mock interviews, and career growth roadmap tools.
          </p>

          <div className="pt-2 flex flex-wrap gap-3">
            <button
              onClick={onOpenFounderModal}
              className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-extrabold text-xs rounded-xl shadow-lg transition-all flex items-center space-x-2 cursor-pointer"
            >
              <Award className="w-4 h-4 text-amber-300" />
              <span>Meet Founder Siddartha Jamandla</span>
            </button>
            <button
              onClick={() => onNavigateTab('input')}
              className="px-5 py-2.5 bg-white/10 hover:bg-white/20 text-white font-bold text-xs rounded-xl border border-white/20 transition-all flex items-center space-x-2 cursor-pointer"
            >
              <span>Explore Resume Analyzer</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* FOUNDER & ABOUT ME SECTION */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-10 shadow-xl space-y-8 relative overflow-hidden">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 pb-6 border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center space-x-5">
            <div className="w-20 h-20 sm:w-24 sm:h-24 rounded-2xl bg-gradient-to-br from-blue-600 via-indigo-700 to-slate-900 flex items-center justify-center text-amber-300 border-4 border-white dark:border-slate-800 shadow-xl shrink-0">
              <Award className="w-10 h-10 sm:w-12 sm:h-12" />
            </div>
            <div className="space-y-1">
              <div className="flex items-center space-x-2">
                <h2 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white">
                  Siddartha Jamandla
                </h2>
                <span className="px-2.5 py-0.5 bg-blue-100 dark:bg-blue-950 text-blue-800 dark:text-blue-300 text-[10px] font-extrabold rounded-full uppercase">
                  Founder & Chief Architect
                </span>
              </div>
              <p className="text-xs sm:text-sm font-bold text-blue-600 dark:text-blue-400">
                AIML Engineer & AI Systems Architect
              </p>
              <div className="flex items-center space-x-1.5 text-xs text-slate-500 dark:text-slate-400 font-medium">
                <MapPin className="w-3.5 h-3.5 text-red-500 shrink-0" />
                <span>Hyderabad, Telangana, India — 500013</span>
              </div>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 w-full md:w-auto">
            <a
              href="mailto:jamandlasiddartha@gmail.com"
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs rounded-xl transition-colors flex items-center space-x-1.5 cursor-pointer shadow-xs"
            >
              <Mail className="w-3.5 h-3.5" />
              <span>jamandlasiddartha@gmail.com</span>
            </a>
            <a
              href="https://www.linkedin.com/in/siddartha-jamandla-97350b384?utm_source=share_via&utm_content=profile&utm_medium=member_android"
              target="_blank"
              rel="noreferrer"
              className="px-3.5 py-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs rounded-xl transition-colors flex items-center space-x-1.5 cursor-pointer"
            >
              <Linkedin className="w-3.5 h-3.5" />
              <span>LinkedIn</span>
            </a>
            <a
              href="https://github.com/siddarthajamandla-sketch"
              target="_blank"
              rel="noreferrer"
              className="px-3.5 py-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs rounded-xl transition-colors flex items-center space-x-1.5 cursor-pointer"
            >
              <Github className="w-3.5 h-3.5" />
              <span>GitHub</span>
            </a>
          </div>
        </div>

        {/* ABOUT ME BIOGRAPHY */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 space-y-4">
            <h3 className="text-base font-black text-slate-900 dark:text-white flex items-center space-x-2">
              <GraduationCap className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              <span>About Me & Background</span>
            </h3>

            <p className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
              Hello! I am <strong>Siddartha Jamandla</strong>, an <strong>Artificial Intelligence & Machine Learning (AIML) Engineering student</strong> based in <strong>Hyderabad, Telangana, India (Pincode: 500013)</strong>.
            </p>

            <p className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
              My expertise centers around building intelligent machine learning algorithms, deep neural network pipelines, natural language processing models, and high-performance full-stack web applications. I designed and built <strong>CAREER PLUS+</strong> to solve real-world career bottlenecks faced by students, developers, and professionals worldwide.
            </p>

            <p className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
              By harnessing our proprietary <strong>CAREER PLUS+ AI engine</strong>, CAREER PLUS+ converts raw resume text into actionable recruiter insight, prepares candidates with real-time speech and posture-analyzed mock interviews, and guides professionals toward high-paying tech roles with personalized career roadmaps.
            </p>

            <div className="p-4 bg-slate-50 dark:bg-slate-950/80 border border-slate-200 dark:border-slate-800 rounded-2xl space-y-2">
              <h4 className="text-xs font-black uppercase text-slate-900 dark:text-slate-200 flex items-center space-x-2">
                <Brain className="w-4 h-4 text-amber-500" />
                <span>Founder's Personal Statement</span>
              </h4>
              <blockquote className="text-xs italic text-slate-600 dark:text-slate-400 leading-relaxed">
                "As an AIML student, my goal is to bridge the gap between complex artificial intelligence research and practical, everyday software tools that uplift people. CAREER PLUS+ represents my commitment to creating transparent, empowering, and accessible AI tools for every ambitious job candidate."
              </blockquote>
            </div>
          </div>

          {/* SIDEBAR: TECHNICAL SKILLS & EDUCATION */}
          <div className="space-y-4 bg-slate-50 dark:bg-slate-950/60 p-5 rounded-2xl border border-slate-200 dark:border-slate-800">
            <h4 className="text-xs font-black uppercase tracking-wider text-slate-900 dark:text-slate-200 flex items-center space-x-2">
              <Code className="w-4 h-4 text-blue-600" />
              <span>Core Engineering Stack</span>
            </h4>

            <div className="space-y-3 text-xs">
              <div>
                <span className="font-extrabold text-slate-900 dark:text-white block mb-1">AIML & Data Science:</span>
                <div className="flex flex-wrap gap-1.5">
                  {['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn', 'Generative AI', 'NLP', 'Computer Vision'].map((s) => (
                    <span key={s} className="px-2 py-1 bg-blue-100 dark:bg-blue-950 text-blue-800 dark:text-blue-300 font-bold text-[10px] rounded-lg">
                      {s}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="font-extrabold text-slate-900 dark:text-white block mb-1">Web & Cloud Architecture:</span>
                <div className="flex flex-wrap gap-1.5">
                  {['React 18', 'TypeScript', 'Node.js', 'Express', 'Tailwind CSS', 'Vite', 'REST APIs', 'Cloud Run'].map((s) => (
                    <span key={s} className="px-2 py-1 bg-slate-200 dark:bg-slate-800 text-slate-800 dark:text-slate-200 font-bold text-[10px] rounded-lg">
                      {s}
                    </span>
                  ))}
                </div>
              </div>

              <div className="pt-2 border-t border-slate-200 dark:border-slate-800">
                <span className="font-extrabold text-slate-900 dark:text-white block mb-1">Education & Location:</span>
                <p className="text-slate-600 dark:text-slate-400 leading-snug">
                  B.Tech in AIML Engineering<br />
                  Hyderabad, Telangana, India (500013)
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ALL PLATFORM FEATURES CATALOG */}
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <h2 className="text-2xl font-black text-slate-900 dark:text-white">
              Complete Feature Ecosystem
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Explore all 18+ career intelligence modules built into CAREER PLUS+.
            </p>
          </div>

          <span className="px-3 py-1 bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300 text-xs font-extrabold rounded-full self-start sm:self-auto">
            18 Active Modules
          </span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {platformFeatures.map((feat) => {
            const Icon = feat.icon;
            return (
              <div
                key={feat.id}
                onClick={() => onNavigateTab(feat.id)}
                className="p-5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl hover:border-blue-500 dark:hover:border-blue-500 shadow-xs hover:shadow-md transition-all cursor-pointer group flex flex-col justify-between space-y-3"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <div className="p-2.5 bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 rounded-xl group-hover:scale-110 transition-transform">
                      <Icon className="w-5 h-5" />
                    </div>
                    <span className="px-2 py-0.5 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 text-[10px] font-extrabold rounded-md uppercase">
                      {feat.cat}
                    </span>
                  </div>

                  <h3 className="text-sm font-extrabold text-slate-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                    {feat.label}
                  </h3>

                  <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                    {feat.desc}
                  </p>
                </div>

                <div className="pt-2 flex items-center text-xs font-bold text-blue-600 dark:text-blue-400 group-hover:translate-x-1 transition-transform">
                  <span>Launch Feature</span>
                  <ArrowRight className="w-3.5 h-3.5 ml-1" />
                </div>
              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
};
